### ISSUE TITLE
타임아웃 시간 설정 기능

### ISSUE THREAD

**Issue by chilyoon** [chilyoon/Badwords_timeout_bot#2]
명령어로 타임아웃 시간을 설정할 수 있는 기능 추가

**Comment by kzlwon** [comment]
$duration으로 타임아웃 시간 설정 가능(기본 설정값 오류)

c96db892ad1c8df7ac516782ce70ccfb7b7b9764

**Comment by chilyoon** [comment]
기본 설정값 오류 수정
f871d5507237259e68f920f12a36529ee32c9db9
